### ISSUE TITLE
Gem::Conflict Error

### ISSUE THREAD

**Issue by ryanmansfield** [exercism/ruby#1013]
I have followed all the instructions on installing and configuring exercism.  Upon starting the hello world exercise, I run into issues.  When I run `ruby hello_world_test.rb` to start, the test results come back the same way as in the video.  Then I create the `hello_world.rb` file and run the test again, I do not get the same error as in the video.  Instead, I get 

```
Traceback (most recent call last):
	9: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.13.0/lib/minitest.rb:68:in `block in autorun'
	8: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.13.0/lib/minitest.rb:126:in `run'
	7: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.13.0/lib/minitest.rb:97:in `load_plugins'
	6: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.13.0/lib/minitest.rb:97:in `each'
	5: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.13.0/lib/minitest.rb:103:in `block in load_plugins'
	4: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	3: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	2: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/minitest/rails_plugin.rb:4:in `<top (required)>'
	1: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:117:in `require'
/Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:117:in `require': cannot load such file -- rails/test_unit/reporter (LoadError)
	12: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.13.0/lib/minitest.rb:68:in `block in autorun'
	11: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.13.0/lib/minitest.rb:126:in `run'
	10: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.13.0/lib/minitest.rb:97:in `load_plugins'
	 9: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.13.0/lib/minitest.rb:97:in `each'
	 8: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.13.0/lib/minitest.rb:103:in `block in load_plugins'
	 7: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/minitest/rails_plugin.rb:4:in `<top (required)>'
	 4: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	 3: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:123:in `rescue in require'
	 2: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems.rb:217:in `try_activate'
	 1: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/specification.rb:1418:in `activate'
/Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/specification.rb:2302:in `raise_if_conflicts': Unable to activate railties-5.2.3, because activesupport-6.0.0 conflicts with activesupport (= 5.2.3) (Gem::ConflictError)
	13: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.13.0/lib/minitest.rb:68:in `block in autorun'
	12: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.13.0/lib/minitest.rb:126:in `run'
	11: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.13.0/lib/minitest.rb:97:in `load_plugins'
	10: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.13.0/lib/minitest.rb:97:in `each'
	 9: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-5.13.0/lib/minitest.rb:103:in `block in load_plugins'
	 8: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 7: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/minitest/rails_plugin.rb:4:in `<top (required)>'
	 5: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	 4: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:123:in `rescue in require'
	 3: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems.rb:216:in `try_activate'
	 2: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems.rb:223:in `rescue in try_activate'
	 1: from /Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/specification.rb:1418:in `activate'
/Users/ryanmansfield/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/specification.rb:2302:in `raise_if_conflicts': Unable to activate railties-5.2.3, because activesupport-6.0.0 conflicts with activesupport (= 5.2.3) (Gem::ConflictError)
```

How can I correct this?

**Comment by kotp** [comment]
When you do `gem list` I don't see any of these gems listed, so they are not required for Exercism.  What happens if you remove the gems.

`gem uninstall activesupport railties`

Then run the tests again.  If that still doesn't work, please let us know the error and maybe the contents of `hello-world.rb`.  I am assuming the test file matches the one in the "Test suite" tab on the website.

**Comment by kotp** [comment]
@ryanmansfield I am closing this, but feel free to comment and reopen, if this is not resolved.  Let us know how you resolved it, in case someone else hits the same issue, so they may have a chance to find a solution here as well.

Thanks for reporting this.
